apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default

  source:        
    repoURL: https://github.com/shehryargit/chat-app-argo-cd.git
    targetRevision: HEAD
    path: dev/frontend
    helm: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: my-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
   